# Generated by Django 4.2.3 on 2023-07-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pieces_per_package',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
